export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'; 
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS'; 
export const FETCH_USERS_BEGIN   = 'FETCH_USERS_BEGIN';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
